DROP INDEX IF EXISTS idx_notifications_user_unread;
DROP INDEX IF EXISTS idx_product_offers_product_id;
DROP INDEX IF EXISTS idx_products_category_id;
DROP INDEX IF EXISTS idx_products_name_trgm;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS product_offers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS roledictionary CASCADE;
DROP EXTENSION IF EXISTS pg_trgm;