DROP INDEX IF EXISTS idx_notifications_user_unread;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS product_offers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS roledictionary CASCADE;